all: ~/bin/macro_expansion ~/bin/error_track

~/bin/macro_expansion : macro_expansion.go
	go build  -o ~/bin/macro_expansion macro_expansion.go
~/bin/error_track : error_track.go
	go build  -o ~/bin/error_track error_track.go
